// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgIndex.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "MsgIndex.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace MsgProto {

namespace {

const ::google::protobuf::EnumDescriptor* MsgIndex_descriptor_ = NULL;

}  // namespace


void protobuf_AssignDesc_MsgIndex_2eproto() {
  protobuf_AddDesc_MsgIndex_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "MsgIndex.proto");
  GOOGLE_CHECK(file != NULL);
  MsgIndex_descriptor_ = file->enum_type(0);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_MsgIndex_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_MsgIndex_2eproto() {
}

void protobuf_AddDesc_MsgIndex_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\016MsgIndex.proto\022\010MsgProto*\321\007\n\010MsgIndex\022"
    "\022\n\016MSG_INDEX_INIT\020\000\022\017\n\013MSG_MsgHead\020\001\022\025\n\021"
    "MSG_MsgBeginLogin\020\002\022\031\n\025MSG_MsgC2SReqRole"
    "Info\020\003\022\031\n\025MSG_MsgS2CAckRoleInfo\020\004\022\034\n\030MSG"
    "_MsgS2CUpdateRoleInfo\020\005\022\031\n\025MSG_MsgS2CNot"
    "ifyError\020\006\022\023\n\017MSG_MsgEndLogin\020\007\022\030\n\024MSG_M"
    "sgBeginBigWorld\020\010\022\026\n\022MSG_MsgC2SReqMarch\020"
    "\t\022\026\n\022MSG_MsgS2CAckMarch\020\n\022\025\n\021MSG_MsgS2CN"
    "ewNode\020\013\022\030\n\024MSG_MsgC2SReqDstView\020\014\022\030\n\024MS"
    "G_MsgS2CAckDstView\020\r\022\033\n\027MSG_MsgC2SReqMin"
    "eDetail\020\016\022\033\n\027MSG_MsgS2CAckMineDetail\020\017\022\033"
    "\n\027MSG_MsgC2SReqLeaveWorld\020\020\022\034\n\030MSG_MsgC2"
    "SReqInvestigate\020\021\022\035\n\031MSG_MsgC2SReqArmyBa"
    "ckHome\020\022\022\026\n\022MSG_MsgEndBigWorld\020\023\022\024\n\020MSG_"
    "MsgBeginChat\020\024\022\025\n\021MSG_MsgC2SReqChat\020\025\022\025\n"
    "\021MSG_MsgS2CAckChat\020\026\022\026\n\022MSG_MsgS2CGMResu"
    "lt\020\027\022\022\n\016MSG_MsgEndChat\020\030\022\026\n\022MSG_MsgBegin"
    "Report\020\031\022\027\n\023MSG_MsgC2SReqReport\020\032\022\027\n\023MSG"
    "_MsgS2CAckReport\020\033\022\034\n\030MSG_MsgC2SReqFight"
    "Report\020\034\022\034\n\030MSG_MsgS2CAckFightReport\020\035\022\035"
    "\n\031MSG_MsgC2SReqInvestReport\020\036\022\035\n\031MSG_Msg"
    "S2CAckInvestReport\020\037\022\024\n\020MSG_MsgEndReport"
    "\020 \022\024\n\020MSG_MsgBeginBoss\020!\022\030\n\024MSG_MsgS2CNo"
    "tifyBoss\020\"\022\032\n\026MSG_MsgS2CNotifyTurret\020#\022\032"
    "\n\026MSG_MsgS2CTurretAttack\020$\022\022\n\016MSG_MsgEnd"
    "Boss\020%", 1006);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "MsgIndex.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_MsgIndex_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_MsgIndex_2eproto {
  StaticDescriptorInitializer_MsgIndex_2eproto() {
    protobuf_AddDesc_MsgIndex_2eproto();
  }
} static_descriptor_initializer_MsgIndex_2eproto_;
const ::google::protobuf::EnumDescriptor* MsgIndex_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MsgIndex_descriptor_;
}
bool MsgIndex_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
    case 12:
    case 13:
    case 14:
    case 15:
    case 16:
    case 17:
    case 18:
    case 19:
    case 20:
    case 21:
    case 22:
    case 23:
    case 24:
    case 25:
    case 26:
    case 27:
    case 28:
    case 29:
    case 30:
    case 31:
    case 32:
    case 33:
    case 34:
    case 35:
    case 36:
    case 37:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace MsgProto

// @@protoc_insertion_point(global_scope)
