// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgIndex.proto

#ifndef PROTOBUF_MsgIndex_2eproto__INCLUDED
#define PROTOBUF_MsgIndex_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
// @@protoc_insertion_point(includes)

namespace MsgProto {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_MsgIndex_2eproto();
void protobuf_AssignDesc_MsgIndex_2eproto();
void protobuf_ShutdownFile_MsgIndex_2eproto();


enum MsgIndex {
  MSG_INDEX_INIT = 0,
  MSG_MsgHead = 1,
  MSG_MsgBeginLogin = 2,
  MSG_MsgC2SReqRoleInfo = 3,
  MSG_MsgS2CAckRoleInfo = 4,
  MSG_MsgS2CUpdateRoleInfo = 5,
  MSG_MsgS2CNotifyError = 6,
  MSG_MsgEndLogin = 7,
  MSG_MsgBeginBigWorld = 8,
  MSG_MsgC2SReqMarch = 9,
  MSG_MsgS2CAckMarch = 10,
  MSG_MsgS2CNewNode = 11,
  MSG_MsgC2SReqDstView = 12,
  MSG_MsgS2CAckDstView = 13,
  MSG_MsgC2SReqMineDetail = 14,
  MSG_MsgS2CAckMineDetail = 15,
  MSG_MsgC2SReqLeaveWorld = 16,
  MSG_MsgC2SReqInvestigate = 17,
  MSG_MsgC2SReqArmyBackHome = 18,
  MSG_MsgEndBigWorld = 19,
  MSG_MsgBeginChat = 20,
  MSG_MsgC2SReqChat = 21,
  MSG_MsgS2CAckChat = 22,
  MSG_MsgS2CGMResult = 23,
  MSG_MsgEndChat = 24,
  MSG_MsgBeginReport = 25,
  MSG_MsgC2SReqReport = 26,
  MSG_MsgS2CAckReport = 27,
  MSG_MsgC2SReqFightReport = 28,
  MSG_MsgS2CAckFightReport = 29,
  MSG_MsgC2SReqInvestReport = 30,
  MSG_MsgS2CAckInvestReport = 31,
  MSG_MsgEndReport = 32,
  MSG_MsgBeginBoss = 33,
  MSG_MsgS2CNotifyBoss = 34,
  MSG_MsgS2CNotifyTurret = 35,
  MSG_MsgS2CTurretAttack = 36,
  MSG_MsgEndBoss = 37
};
bool MsgIndex_IsValid(int value);
const MsgIndex MsgIndex_MIN = MSG_INDEX_INIT;
const MsgIndex MsgIndex_MAX = MSG_MsgEndBoss;
const int MsgIndex_ARRAYSIZE = MsgIndex_MAX + 1;

const ::google::protobuf::EnumDescriptor* MsgIndex_descriptor();
inline const ::std::string& MsgIndex_Name(MsgIndex value) {
  return ::google::protobuf::internal::NameOfEnum(
    MsgIndex_descriptor(), value);
}
inline bool MsgIndex_Parse(
    const ::std::string& name, MsgIndex* value) {
  return ::google::protobuf::internal::ParseNamedEnum<MsgIndex>(
    MsgIndex_descriptor(), name, value);
}
// ===================================================================


// ===================================================================


// ===================================================================


// @@protoc_insertion_point(namespace_scope)

}  // namespace MsgProto

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::MsgProto::MsgIndex> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::MsgProto::MsgIndex>() {
  return ::MsgProto::MsgIndex_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_MsgIndex_2eproto__INCLUDED
